package manazashi

var ignoredDirs = map[string]bool{
	".bundle":        true,
	".cache":         true,
	".git":           true,
	".gradle":        true,
	".hg":            true,
	".idea":          true,
	".mypy_cache":    true,
	".pytest_cache":  true,
	".ruff_cache":    true,
	".svn":           true,
	".terraform":     true,
	".venv":          true,
	".vscode":        true,
	"__pycache__":    true,
	"bazel-bin":      true,
	"bazel-out":      true,
	"bazel-testlogs": true,
	"build":          true,
	"coverage":       true,
	"deps":           true,
	"dist":           true,
	"node_modules":   true,
	"out":            true,
	"pkg":            true,
	"target":         true,
	"tmp":            true,
	"vendor":         true,
	"venv":           true,
}

var binaryExts = map[string]bool{
	".7z":      true,
	".a":       true,
	".bin":     true,
	".bmp":     true,
	".bundle":  true,
	".class":   true,
	".dll":     true,
	".dylib":   true,
	".exe":     true,
	".gif":     true,
	".ico":     true,
	".jar":     true,
	".jpeg":    true,
	".jpg":     true,
	".lock":    true,
	".mp3":     true,
	".mp4":     true,
	".o":       true,
	".pdf":     true,
	".png":     true,
	".pyc":     true,
	".rlib":    true,
	".so":      true,
	".sqlite":  true,
	".sqlite3": true,
	".wasm":    true,
	".wav":     true,
	".webp":    true,
	".zip":     true,
}

var langByExt = map[string]string{
	".bash":  "shell",
	".c":     "c",
	".cc":    "cpp",
	".cljs":  "clojure",
	".clj":   "clojure",
	".cpp":   "cpp",
	".cs":    "csharp",
	".css":   "css",
	".cxx":   "cpp",
	".el":    "elisp",
	".ex":    "elixir",
	".exs":   "elixir",
	".go":    "go",
	".h":     "c",
	".hpp":   "cpp",
	".hs":    "haskell",
	".html":  "html",
	".java":  "java",
	".js":    "javascript",
	".jsx":   "javascript",
	".kt":    "kotlin",
	".kts":   "kotlin",
	".lua":   "lua",
	".mjs":   "javascript",
	".php":   "php",
	".py":    "python",
	".rake":  "ruby",
	".rb":    "ruby",
	".rs":    "rust",
	".scala": "scala",
	".scm":   "scheme",
	".sh":    "shell",
	".swift": "swift",
	".ts":    "typescript",
	".tsx":   "typescript",
	".tf":    "terraform",
	".vue":   "vue",
	".zsh":   "shell",
}

var langByName = map[string]string{
	"Brewfile":   "ruby",
	"Dockerfile": "dockerfile",
	"Gemfile":    "ruby",
	"Justfile":   "make",
	"Makefile":   "make",
	"Rakefile":   "ruby",
}
